services:
  # Kowl (Kafka Web UI)
  kowl:
    image: quay.io/cloudhut/kowl:latest
    container_name: kowl
    ports:
      - "8080:8080"  # 将 Kowl Web UI 暴露在本地 8080 端口
    environment:
      KAFKA_BROKERS: "kafka:9092"  # 使用服务名称访问 Kafka
    depends_on:
      - kafka   


  # Kafka (KRaft mode)
  kafka:
    image: bitnami/kafka:3.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      ALLOW_PLAINTEXT_LISTENER: yes  # 添加这一行
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # 自动创建topic   
   
    volumes:
      - ./kafka-logs:/tmp/kraft-combined-logs

networks:
  default:
    name: kowl-kafka-network
