version: "3.8"

services:
  # Kowl (Kafka Web UI)
  kowl:
    image: quay.io/cloudhut/kowl:latest
    container_name: kowl
    ports:
      - "8080:8080" # 将 Kowl Web UI 暴露在本地 8080 端口
    environment:
      KAFKA_BROKERS: "kafka:19092" # 这里改成 Docker 内部的 Kafka 地址
    depends_on:
      - kafka

  # Kafka (KRaft mode)
  kafka:
    image: bitnami/kafka:3.4.0
    container_name: kafka
    ports:
      - "9092:9092" # 宿主机访问 Kafka
      - "19092:19092" # Docker 内部访问 Kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,DOCKER://:19092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKER://kafka:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER # 让 Kafka 内部通信使用 DOCKER 监听
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # 自动创建 topic
    volumes:
      - ./kafka-logs:/tmp/kraft-combined-logs

networks:
  default:
    name: kowl-kafka-network
