version: '3.3'
services:
  mysql8:
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "1q2w3e"  #root管理员用户密码
      MYSQL_USER: "yuanjinzhong"  #创建test用户
      MYSQL_PASSWORD: "1q2w3e" #设置test用户的密码
    command:
         --character-set-server=utf8mb4
         --collation-server=utf8mb4_unicode_ci
         --max_connections=3000
    image: "docker.io/mysql:8.0.26"  
    restart: always
    container_name: "mysql8.0"
    volumes:
      #mysql数据库挂载到host物理机目录
      - "./data:/var/lib/mysql"
      #容器的配置目录挂载到host物理机目录
      - "./conf/my.cnf:/etc/my.cnf"
      # 挂载宿主机的时区文件
      - "/etc/localtime:/etc/localtime:ro"  
    ports:
      - "23306:3306" #host物理直接映射端口
