version: '3.8'

services:
  # Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

networks:
  default:
    name: redis-network
